version: "3.8"

services:
  nest-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start:dev
    volumes:
      - ./src:/opt/app/src:z
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 80
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWD: ${POSTGRES_PASSWORD:-changeme}
      DB_NAME: movies
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3000:80

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin:z
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
